config/routes.rb
Rails.application.routes.draw do



  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', sign_up: 'register' }

  resources :users, only: %i[ index show] do
    resources :shops, only: %i[index]
    resources :foods, except: %i[update]
    resources :recipes, except: %i[update] do
      resources :recipe_foods, only: %i[new create]
    end
    resources :public, only: %i[index]
  end

  root 'users#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)

    if user.is? :admin
      can :manage, :all
    else
      can :manage, Food, user_id: user.id
      can :manage, Recipe, user_id: user.id
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  validates :name, presence: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :user
  has_many :recipe_food, dependent: :destroy

  #  Shows the count of food for a user
  def self.total_food(user_id)
    Food.where(user_id: user_id).count
  end

  # Food value total count
  def self.food_money(user_id)
    Food.where(user_id: user_id).sum(:price)
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
  validates :cooking_time, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :user
  has_many :recipe_food, dependent: :destroy

  def self.recipe_update_public(recipe_id)
    recipe = Recipe.find(recipe_id)
    recipe.update(public: !recipe.public)
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  def self.total_value_of_food(user_id)
    sum = 0
    foods = Food.where(user_id: user_id)
    foods.each do |food|
      recipe = RecipeFood.recipe_quantity(food.id)
      sum += (recipe.quantity * food.price) if RecipeFood.quantity?(food.id)
    end
    sum
  end

  def self.recipe_quantity(food_id)
    recipe = RecipeFood.where(food_id: food_id)
    recipe[0]
  end

  def self.quantity?(food_id)
    RecipeFood.find_by(food_id: food_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :food, dependent: :destroy
  has_many :recipe, dependent: :destroy

  # authorization Roles
  Roles = %i[admin default].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def show; end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(
      name: allowed_params[:name],
      price: allowed_params[:price],
      measurement_unit: allowed_params[:measurement_unit],
      user_id: current_user.id
    )

    if @food.save
      redirect_to user_foods_path(current_user.id), notice: 'Successfully added food'

    else
      render 'new'
    end
  end

  def destroy
    @food = Food.find(params[:id]).destroy

    redirect_to user_foods_path(current_user.id), notice: 'Successfully deleted food'
  end

  private

  def allowed_params
    params.require(:food).permit(:name, :price, :measurement_unit)
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def index
    @recipes = Recipe.all
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe_food = RecipeFood.new
    @foods = Food.all
  end

  def create
    @recipe_food = RecipeFood.new(
      quantity: allowed_params[:quantity],
      food_id: allowed_params[:food_id],
      recipe_id: params[:recipe_id]
    )

    if @recipe_food.save
      redirect_to user_recipe_path(current_user.id, params[:recipe_id]), notice: 'Succefully added quatity of food'
    else
      redirect_to new_user_recipe_recipe_food_path(current_user.id, params[:recipe_id]),
                  alert: 'Food quatity not added'
    end
  end

  private

  def allowed_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(name: recipe_params[:name],
                         preparation_time: recipe_params[:preparation_time],
                         cooking_time: recipe_params[:cooking_time],
                         description: recipe_params[:description],
                         public: recipe_params[:public],
                         user_id: current_user.id)
    respond_to do |format|
      format.html do
        if @recipe.save
          flash[:notice] = 'Recipe created successfully.'
          redirect_to "/users/#{@recipe.user.id}/recipes/"
        else
          flash[:notice] = 'Recipe creation failed. Try again'
          render :new
        end
      end
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @foods = Food.all
  end

  def destroy
    @recipe = Recipe.find(params[:id]).destroy
    redirect_to user_recipes_path(current_user.id), notice: 'Recipe removed'
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @foods = Food.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipes_foods_helper.rb
module RecipesFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<div class = 'container  pt-4' >
<div class = "container btn_div">
  <%= link_to 'Add food', new_user_food_path(params[:user_id]), class: 'btn btn-primary text-light text-decoration-none' %>
</div>


<table class="table table-striped table-hover mt-5">
  <thead>
    <tr>
     <th scope="col">#</th>
      <th scope="col">Food</th>
      <th scope="col">Measurement Unit</th>
      <th scope="col">Unit Price</th>
      <th scope="col">Action</th>
    </tr>
  </thead>

  <tbody>
   <% @foods.each.with_index do |food, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td> <%= food.name %></td>
        <td><%= food.measurement_unit %></td>
        <td><%= '$' + food.price.to_s %></td>
        <td>
          <% if can? :destroy, food %>
            <%= button_to 'Delete', "/users/#{current_user.id}/foods/#{food.id}", method: :delete, class: 'btn btn-primary text-light' %>
          <%end%>
        </td>
      </tr>
    <%end%> 
  </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<div class ='container pt-4 mb-4'>
  <h1 class = 'text-center mb-4 mt-3'> Add Food </h1> 
  <div class = 'container col-6'>
    <%= form_with model: @food, url: user_foods_path, scope: :food  do |form| %>
 
      <%= form.text_field :name, class:"form-control mb-3", id: 'name', placeholder: 'Name of food', aria_label: "Name of food"  %>
   
      <%= form.text_field :price, class: "form-control mb-3", id: 'price', placeholder: "Price of food (in dollars)", aria_label: "Price of food" %>
   
      <%= form.select :measurement_unit, options_for_select([['Selelct Measurement unit', 'units'],['Grams', 'grams'], ['Units', 'units']],"Selelct Measurement unit"), {}, class:'form-control select', id: 'measurement_unit', aria_label: "form-select-sm example" %>
      <div>
        <%= form.submit 'Create Food', class: 'btn btn-primary text-light mt-3' %>
      </div>
    <%end%>
  </div>
</div>

app/views/helper/_food_quantity.html.erb
 <table class="table table-striped table-hover mt-5">
  <thead>
    <tr>
     <th scope="col">#</th>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Value</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>

  <tbody>
   <% @foods.each.with_index do |food, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td> <%= food.name %></td>
        <td>
          <% recipe = RecipeFood.recipe_quantity(food.id) || 0 %>
          <%if recipe != 0 %>
            <%= recipe_val = recipe.quantity %>g
          <%else%>
            <%= recipe_val = recipe %>g
          <%end%>
        </td>
        <td>$<%= recipe_val * food.price %></td>
        <td class = 'd-flex justify-content-around'>
        <% if can? :destroy, food%>
          <%= button_to 'Modify', edit_user_recipe_path(current_user.id, food.id), class: 'btn btn-primary text-light' %>
          <%= button_to 'Delete', "/users/#{current_user.id}/foods/#{food.id}", method: :delete, class: 'btn btn-primary text-light' %>
        <%else%>
          <%= button_to "Modify", user_shops_path(current_user.id) , class: 'btn btn-secondary text-light disabled' %>
          <%= button_to "Delete", user_shops_path(current_user.id), class: 'btn btn-secondary text-light disabled' %>
        <%end%>
       </td>
      </tr>
    <%end%> 
  </tbody>
  </table>

app/views/helper/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<div class="container-fluid">
  <%= link_to 'Recipe 2M', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
  data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to current_user.name, users_path , class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Foods', user_foods_path(current_user.id) , class: "nav-link" %>
        </li>
         <li class="nav-item">
          <%= link_to 'Recipe', user_recipes_path(current_user.id) , class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Public-Recipe',  user_public_index_path(current_user.id) , class: "nav-link" %>
       </li>
        <li class="nav-item">
          <%= button_to 'Log Out', destroy_user_session_path , method: :delete, class: "nav-link btn btn-primary-outline" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Register', new_user_registration_path , class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log In', new_user_session_path , class: "nav-link" %>
        </li>
    
      <% end %>
    </ul>
  </div>
</div>
</nav>

app/views/helper/_shoplist.html.erb
 <table class="table table-striped table-hover mt-5">
  <thead>
    <tr>
     <th scope="col">#</th>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>
    </tr>
  </thead>

  <tbody>
   <% @foods.each.with_index do |food, index| %>
   <% if food.user_id == current_user.id %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td> <%= food.name %></td>
        <td>
          <% recipe = RecipeFood.recipe_quantity(food.id) || 0 %>
          <%if recipe != 0 %>
            <%= recipe_val = recipe.quantity %>g
          <%else%>
            <%= recipe_val = recipe %>g
          <%end%>
        </td>
        <td>$<%= recipe_val * food.price %></td>
    <%end%> 
      </tr>
      <%end%>
  </tbody>
  </table>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>Recipe</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
 
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  
  </head>
  <body>
  <%= render 'helper/nav' %>
    
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
     <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


  </body>
</html>

app/views/recipe_foods/new.html.erb
<% def form_select%>
<% array = []%>
  <% @foods.each do |food|%>
    <% unless RecipeFood.quantity?(food.id) %>
      <% array.push(["#{food.name}","#{food.id}"])%>
    <%end%>
  <%end%>
  <%array%>
<%end%>


<div class = 'container pb-4'>
  <h1 class ='text-center mt-4' >Add Food Quantity</h1>

  <div class = 'container col-4'>
    <%= form_with model: @recipe_food, url: user_recipe_recipe_foods_path, scope: :recipe_food  do |form| %>
      <%= form.label 'Select a food', class: 'fs-5' %>
      <%= form.select :food_id, options_for_select(form_select) , {}, class:'form-control select mb-4', aria_label: "form-select-sm example" %>
      <%= form.label 'Quantity', class: 'fs-5' %>
      <%= form.text_field :quantity, class:'form-control select mb-4' %>
      <%= form.submit 'Add quantity', class: 'btn btn-primary text-light' %>
    <%end%>
  </div>
</div>

app/views/recipes/index.html.erb
<% @recipes.each do |recipe| %>
   <% if can? :read, recipe%>
     <div class="card mb-4 border-5 p-3 m-3 bg-success bg-gradient" style="min-width: 540px;">
        <div class="row g-0">
           <div class="col-md-4">
              <h3 class="m-3"><%= link_to recipe.name, user_recipe_path(current_user.id, recipe.id) %></h3>
              <% if can? :destroy, recipe %>
               <%= button_to 'Remove',"/users/#{current_user.id}/recipes/#{recipe.id}", method: :delete, class: "btn btn-info m-3" %>
              <%end%>
           </div>
           <div class="col-md-8">
              <div class="card-body">
                 <p class="card-text"> <%= recipe.description %> </p>
              </div>
           </div>
        </div>
     </div>
   <%end%>
   <% end %> 
<%= link_to 'Add Recipes', new_user_recipe_path(params[:user_id]), class:"btn btn-info m-3"%>

app/views/recipes/new.html.erb
<div class="min-vh-80">
   <h2  class="form-group w-25" style = "padding-left: 10%" >
   New Recipe
   <h2>
   <%= form_with model: @recipe, url:  user_recipes_path, scope: :recipe, html: {class: "recipe-form-c"} do |form| %>  
   <div class="form-group w-25 p-5">
      <%= form.text_field :name, placeholder: "Title", required: true, class: "form-control" ,id: 'name'%><br>
      <%= form.text_field :preparation_time, placeholder: "Preparation Time", required: true, class: "form-control" ,id: 'preparation_time'%><br>
      <%= form.text_field :cooking_time, placeholder: "Cooking Time", required: true, class: "form-control", id: 'cooking_time'%><br>
      <%= form.text_area :description, placeholder: "Description...", rows: 10, required: true,  class: "form-control" ,id: 'description'%>
      <div class="d-flex align-items-center mb-2">
         <%= form.check_box :public %>
         <%= form.label :public, class:"mx-2 fs-6 m-2"%>
      </div>
      <%= form.submit "Create Recipe", class: "btn btn-primary" %>
   </div>
   <% end %> 
</div>
</div>

app/views/recipes/show.html.erb
<div class = "container py-4">
  <h1 class = 'text-center mt-4'><strong> <%= @recipe.name %> </strong></h1>

  <div class = 'container col-8 flex-column mt-4'>
    <div class = 'd-flex justify-content-between'>
      <p>Praration time: <%= @recipe.preparation_time %> hour</p>
      <!-- Default switch -->
      <%= form_with model: @recipe, url: user_recipes_path, scope: :recipe  do |form| %>
        <div class="form-check form-switch">
          <%= form.check_box :public, class: "form-check-input disabled", onchange: "#{Recipe.recipe_update_public(@recipe.id)}", checked: @recipe.public   %>
          <%= form.label :public, 'public', class: "form-check-label"%> 
        </div>
      <%end%>
    </div>
    <div>
      <p> Cooking time: <%= @recipe.cooking_time%> hours </p>
    </div>
    <p> <%= @recipe.description%> </p>
  </div>

  <div class = 'container col-8 d-flex justify-content-between mt-4 mb-4'>
    <%= link_to 'Generate shopping list', user_shops_path(current_user.id), class: 'btn btn-primary text-light' %>
    <% if can? :create, @recipe%>
    <%= link_to 'Add ingredients', new_user_recipe_recipe_food_path(current_user.id, @recipe.id), class: 'btn btn-primary text-light' %>
    <%end%>
  </div>
  <hr class = 'container col-8 mt-3'>

  <%= render 'helper/food_quantity' %>
</div>

  

app/views/recipes_foods/new.html.erb
<% def form_select%>
<% array = []%>
  <% @foods.each do |food|%>
    <% unless RecipeFood.quantity?(food.id) %>
      <% array.push(["#{food.name}","#{food.id}"])%>
    <%end%>
  <%end%>
  <%array%>
<%end%>


<div class = 'container pb-4'>
  <h1 class ='text-center mt-4' >Add Food Quantity</h1>

  <div class = 'container col-4'>
    <%= form_with model: @recipe_food, url: user_recipe_recipe_foods_path, scope: :recipe_food  do |form| %>
      <%= form.label 'Select a food', class: 'fs-5' %>
      <%= form.select :food_id, options_for_select(form_select) , {}, class:'form-control select mb-4', aria_label: "form-select-sm example" %>
      <%= form.label 'Quantity', class: 'fs-5' %>
      <%= form.text_field :quantity, class:'form-control select mb-4' %>
      <%= form.submit 'Add quantity', class: 'btn btn-primary text-light' %>
    <%end%>
  </div>
</div>

app/views/shops/index.html.erb
<div class = 'container pt-4 mb-4'>
  <h1 class= 'text-center mb-4'> Shopping List </h1>

  <div>
    <div class = 'container pt-3 d-flex justify-content-between col-10'>
      <p> <strong>Amount of food items to buy:</strong> <%= Food.total_food(current_user.id)%> </p>
      <p>Total value of food needed: $<%= RecipeFood.total_value_of_food(current_user.id)%> </p>
    </div>
  </div>

  <div class = 'container col-10'>
    <%= render 'helper/shoplist' %>
  </div>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <div class="card mb-4 border-5 p-3 m-3 bg-success bg-gradient" style="min-width: 540px;">
     <div class="fs-2">
        <p> User Name: <%= user.name %></p>
        <p> User Email: <%= user.email %></p>
     </div>
  </div>
  <% end %>